name: invoke-runner
on:
  workflow_dispatch:

jobs:
  invoke-runner:
    uses: m-hammad0/reusable-workflow-POC/.github/workflows/test.yml@v1.0.0
    secrets: inherit
    with:
      passed-var: "this is foo"

  foo:
    needs: [invoke-runner]
    runs-on: ubuntu-latest
    steps:
      - name: TEST 
        run : echo "${{ needs.invoke-runner.outputs.expose_var }}"
  
